[versions]
app-version-string = "4.2.2"
app-version-code = "47"

android_sdk-min = "21"
android_sdk-compile = "34"
wear_sdk-min = "30"
wear_sdk-compile = "33"

ios_target = "11.0"

magister = "1.3.0"

work-android = "2.9.0"

kotlin = "2.0.0"
gradle = "8.2.2"
appcompat = "1.7.0"
material = "1.12.0"
compose = "1.6.11"
compose-android = "1.6.8"
compose-activity = "1.9.0"
material3 = "1.2.1"
ktor = "2.3.10"
decompose = "2.2.3"
moko = "0.24.1"
buildkonfig = "0.13.3"
multiplatform-settings = "1.1.1"
#noinspection GradleDependency # it thinks the jre version is higher than the android version. remove this line to allow IDE checking for version updates again
guava = "31.1-android"
guava-coroutines = "1.8.0"

complete-kotlin = "1.1.0"
colormath = "3.4.0"

kotlin-datetime = "0.5.0"
horologist = "0.5.21"
skiko = "0.7.97"
agp = "8.2.0"
kotlin190 = "1.9.0"
play-services-wearable = "18.2.0"
wear-compose-bom = "2024.06.00"
compose-material = "1.3.1"
compose-material3 = "1.0.0-alpha23"
compose-foundation = "1.3.1"
core-splashscreen = "1.0.1"
wear-phone-interactions = "1.0.1"
richeditor = "1.0.0-rc04"

[libraries]
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose-android" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-android" }
compose-foundationlayout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "compose-android" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose-android" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }

kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-content_negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-serialization_json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging_jvm = { group = "io.ktor", name = "ktor-client-logging-jvm", version.ref = "ktor" }
ktor-client-json_jvm = { group = "io.ktor", name = "ktor-client-json-jvm", version.ref = "ktor" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-ios = { group = "io.ktor", name = "ktor-client-ios", version.ref = "ktor" }

moko-gradle = { group = "dev.icerock.moko", name = "resources-generator", version.ref = "moko" }
moko-resources-core = { group = "dev.icerock.moko", name = "resources", version.ref = "moko" }
moko-resources-compose = { group = "dev.icerock.moko", name = "resources-compose", version.ref = "moko" }

buildkonfig-gradle = { group = "com.codingfeline.buildkonfig", name = "buildkonfig-gradle-plugin", version.ref = "buildkonfig" }

decompose-core = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-compose = { group = "com.arkivanov.decompose", name = "extensions-compose-jetbrains", version.ref = "decompose" }

multiplatform-settings = { group = "com.russhwolf", name = "multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }

magister-api = { group = "dev.tiebe", name = "magisterapi", version.ref = "magister" }

color-math = { group = "com.github.ajalt.colormath", name = "colormath", version.ref = "colormath" }

guava-core = { group = "com.google.guava", name = "guava", version.ref = "guava" }
guava-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "guava-coroutines" }

androidx-work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-android" }

skiko = { group = "org.jetbrains.skiko", name = "skiko", version.ref = "skiko" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "play-services-wearable" }
wear-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "wear-compose-bom" }
wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-wear-compose-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "compose-material" }
androidx-wear-compose-compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "compose-material3" }
compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "compose-foundation" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
androidx-wear-phone-interactions = { group = "androidx.wear", name = "wear-phone-interactions", version.ref = "wear-phone-interactions" }

horologist-compose-layout = { group = "com.google.android.horologist", name = "horologist-compose-layout", version.ref = "horologist" }
horologist-compose-material = { group = "com.google.android.horologist", name = "horologist-compose-material", version.ref = "horologist" }

richeditor = { group = "com.mohamedrejeb.richeditor", name = "richeditor-compose", version.ref = "richeditor" }

[plugins]
mokoresources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko" }
complete_kotlin = { id = "com.louiscad.complete-kotlin", version.ref = "complete-kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }